fn void main () {
    for (int a=0, int b = 20; a < 50 && b >= 15; a++, --b) {
        break;
    }
    
    for TOTO:(;;) {
            random();
            break TOTO;
    }
    
    for(; a < 50; a++) {
        random(); int j = 30;
        continue;
    }

    for(bool c = true;; c= !c) random();  
    
    for(; a < 50; a++) {
        random(); int j = 30;
        continue;
    }

    for(int i = 0; i < 10; ++i) {
        for(int j = 0; j < 20; j++) {
            random();
        }
    }
}